---
title: "Code1"
output: pdf_document
date: "2025-05-06"
---
## Settings
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE)
```
## Reading data frames
```{r}
library(foreign)
library(tidyverse)
library(dplyr)
wave1 <- covid_19_wave1_survey_cls
wave2 <- covid_19_wave2_survey_cls
wave3 <- covid_19_wave3_survey_cls
```
## Exploring dataset, picking the data going to be used in later analysis
```{r}
wave1 <- wave1 %>%
  select(NCDSID, CW1_COVID19, CW1_COVID_HOSPAD, CW1_GHQ, CW1_HHNUM, CW1_FINANCIALMANB, CW1_FINANCIALMAND, CW1_MALAISE_1, CW1_MALAISE_2, CW1_MALAISE_3, CW1_MALAISE_4, CW1_MALAISE_5, CW1_MALAISE_6, CW1_MALAISE_7, CW1_MALAISE_8, CW1_MALAISE_9, CW1_GAD2PHQ2_1, CW1_GAD2PHQ2_2, CW1_GAD2PHQ2_3, CW1_GAD2PHQ2_4)
wave2 <- wave2 %>%
  select(NCDSID, CW2_COVID19, CW2_COVID_HOSPAD, CW2_GHQ, CW2_HHNUM, CW2_FINANCIALMANB, CW2_FINANCIALMAND, CW2_MALAISE_1, CW2_MALAISE_2, CW2_MALAISE_3, CW2_MALAISE_4, CW2_MALAISE_5, CW2_MALAISE_6, CW2_MALAISE_7, CW2_MALAISE_8, CW2_MALAISE_9, CW2_GAD2PHQ2_1, CW2_GAD2PHQ2_2, CW2_GAD2PHQ2_3, CW2_GAD2PHQ2_4)
wave3 <- wave3 %>%
  select(NCDSID, CW3_COVID19, CW3_COVID_HOSPAD, CW3_GHQ, CW3_HHNUM, CW3_FINANCIALMANB, CW3_FINANCIALMAND, CW3_MALAISE_1, CW3_MALAISE_2, CW3_MALAISE_3, CW3_MALAISE_4, CW3_MALAISE_5, CW3_MALAISE_6, CW3_MALAISE_7, CW3_MALAISE_8, CW3_MALAISE_9, CW3_GAD2PHQ2_1, CW3_GAD2PHQ2_2, CW3_GAD2PHQ2_3, CW3_GAD2PHQ2_4)
```
## Data cleaning, maybe we should filter out everyone who does not have a participant ID?
```{r}
wave1 <- wave1 %>%
  filter(NCDSID != "")
wave2 <- wave2 %>%
  filter(NCDSID != "")
wave3 <- wave3 %>%
  filter(NCDSID != "")
```
## I filtered all participants who participated in all three waves of data collections. Now we can look at longitudinal effects.
```{r}
common_ids <- reduce(list(wave1$NCDSID, wave2$NCDSID, wave3$NCDSID), intersect)
wave1_com <- wave1 %>%
  filter(NCDSID %in% common_ids)
wave2_com <- wave2 %>%
  filter(NCDSID %in% common_ids)
wave3_com <- wave3 %>%
  filter(NCDSID %in% common_ids)
```
## Specifying waves, preparing for pivot_long
```{r}
wave1_com <- wave1_com %>%
  mutate(wave = 1)
wave2_com <- wave2_com %>%
  mutate(wave =2)
wave3_com <- wave3_com %>%
  mutate(wave = 3)

```

